image: node:lts-bullseye-slim

cache: &cache
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
  policy: pull

.only: &only
  refs:
    - main
    - merge_requests

.except: &exclude_release
  changes:
    - CHANGELOG.md

.only_release: &only_release
  refs:
    - main
  variables:
    - $CI_COMMIT_AUTHOR == "Alfred Pennyworth <alfred.pennyworth@polymtl.ca>"

stages:
  - install
  - tests
  - release

install:
  stage: install
  only: *only
  script:
    - echo "@backend:registry=https://gitlab.com/api/v4/projects/29618275/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/29618275/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm ci --cache .npm --prefer-offline
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - .npm
    policy: pull-push

lint-and-build:
  stage: tests
  only: *only
  script:
    - npm run format:check
    - npm run lint
    - npm run build
  cache: *cache
  dependencies:
    - install
  artifacts:
    paths:
      - dist/

karma:
  stage: tests
  only: *only
  image: $CI_REGISTRY_IMAGE/headless-chromium:0.0.2
  script:
    - Xvfb :99 -ac -screen 0 1920x1080x24 &
    - npm run test -- --browsers=ChromeHeadlessNoSandbox --watch=false
  cache: *cache
  dependencies:
    - install
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
  artifacts:
    reports:
      cobertura: coverage/client/cobertura-coverage.xml

release:
  stage: release
  only:
    refs:
      - main
  variables:
    GIT_AUTHOR_NAME: Alfred Pennyworth
    GIT_AUTHOR_EMAIL: alfred.pennyworth@polymtl.ca
    GIT_COMMITTER_NAME: Alfred Pennyworth
    GIT_COMMITTER_EMAIL: alfred.pennyworth@polymtl.ca
    GITLAB_TOKEN: $SEMANTIC_RELEASE_TOKEN
  script:
    - npx semantic-release
  cache: *cache
