image: node:lts-bullseye-slim

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
  policy: pull

.only: &only
  refs:
    - main
    - merge_requests

.except: &exclude_release
  changes:
    - CHANGELOG.md

.only_release: &only_release
  refs:
    - main
  variables:
    - $CI_COMMIT_AUTHOR == "Alfred Pennyworth <alfred.pennyworth@polymtl.ca>"

stages:
  - install
  - test

install:
    stage: install
    only: *only
    variables:
      NPM_REGISTRY: $CI_SERVER_HOST/api/v4/projects/$CI_PROJECT_ID/packages/npm/
    script:
      - echo "@backend:registry=https://gitlab.com/api/v4/projects/29618275/packages/npm/" > .npmrc
      - echo "//gitlab.com/api/v4/projects/29618275/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
      - npm ci --cache .npm --prefer-offline
    cache:
      key:
        files:
          - package-lock.json
      paths:
        - node_modules/
        - .npm
      policy: pull-push

static:
  stage: test
  only: *only
  script:
    - prettier --check .
    - npm run lint
  dependencies:
    - install

test:
  stage: test
  only: *only
  image: $CI_REGISTRY_IMAGE/headless-chromium:0.0.1
  script:
    - Xvfb :99 -ac -screen 0 1920x1080x24 &
    - npm run test -- --browsers=ChromeHeadless --watch=false
  dependencies:
    - install
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
